name = "keynub_samples"
description = "Samples for the KeyNub License Dongle Ada crate"
version = "1.1.1"
licenses = "Apache-2.0"
authors = ["KeyNub"]
maintainers = ["KeyNub <info@keynub.com>"]
maintainers-logins = ["ab-tools"]
executables = ["verify_and_read", "rotate_write_key"]

[[depends-on]]
keynub_licdongle = "*"

[[pins]]
keynub_licdongle = { path = "../../bindings/ada" }

[build-switches]
"*".ada_version = "ada12"
"*".style_checks = "no"
